'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens={start:$('#start'),crop:$('#crop'),game:$('#game')};
const cropC=$('#cropCanvas'), cc=cropC.getContext('2d'), gameC=$('#gameCanvas'), gc=gameC.getContext('2d');
let image=null, head=null, crop={x:0,y:0,zoom:1,base:1,rot:0}, pointers=new Map(), drag=null, pinch=null;
let coins=+(localStorage.hhCoins||0), unlocked=JSON.parse(localStorage.hhUnlocked||'["hammer"]'), selected='hammer';
let flat=0, runWon=false, swinging=false, swing={t:0,d:0}, particles=[], shake=0, soundOn=true, audio;
const weapons={
 hammer:{name:'REGULAR HAMMER',icon:'🔨',damage:.20,speed:520,color:'#555',mess:'dust',word:['BONK!','THWACK!','KAPOW!']},
 shark:{name:'HAMMERHEAD SHARK',icon:'🦈',damage:.29,speed:720,color:'#2a73ff',mess:'bubbles',word:['CHOMP-BONK!','FIN-ISHED!','SHARK ATTACK!']},
 toy:{name:'TOY HAMMER',icon:'🧸',damage:.12,speed:280,color:'#f24b9d',mess:'confetti',word:['SQUEAK!','BOOP!','TINY BONK!']}
};
function show(id){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[id].classList.add('active');}
function save(){localStorage.hhCoins=coins;localStorage.hhUnlocked=JSON.stringify(unlocked);$('#coins').textContent=coins;renderWeapons()}
function picker(){const p=$('#photo');p.value='';p.click()}
$('#photo').onchange=async e=>{const file=e.target.files[0];if(!file)return; if(!file.type.startsWith('image/'))return; const url=URL.createObjectURL(file);const im=new Image();im.onload=async()=>{image=im;show('crop');fitCrop();drawCrop();await detectFace();URL.revokeObjectURL(url)};im.onerror=()=>alert('That photo was too mysterious to open. Try another!');im.src=url};
$$('.repick').forEach(b=>b.onclick=()=>{hideWin();picker()});$('#back').onclick=()=>show('start');
function fitCrop(){crop.base=Math.max(700/image.width,700/image.height);crop.zoom=1;crop.x=crop.y=0;crop.rot=0;$('#zoom').value=1;$('#status').textContent='Looking for a head…'}
function drawCrop(){if(!image)return;cc.clearRect(0,0,700,700);cc.save();cc.translate(350+crop.x,350+crop.y);cc.rotate(crop.rot*Math.PI/180);const s=crop.base*crop.zoom;cc.scale(s,s);cc.drawImage(image,-image.width/2,-image.height/2);cc.restore()}
async function detectFace(){if(!('FaceDetector' in window)){setTimeout(()=>$('#status').textContent='Center crop ready — give it a nudge if needed.',450);return}try{const detector=new FaceDetector({fastMode:true,maxDetectedFaces:1});const faces=await detector.detect(image);if(!faces.length)throw 0;const b=faces[0].boundingBox;const desired=350/Math.max(b.width,b.height*.78);crop.zoom=Math.max(.45,Math.min(3.5,desired/crop.base));const s=crop.base*crop.zoom;crop.x=-((b.x+b.width/2)-image.width/2)*s;crop.y=-((b.y+b.height*.48)-image.height/2)*s;$('#zoom').value=crop.zoom;$('#status').textContent='Head acquired! Fine-tune if you like.';drawCrop()}catch(e){$('#status').textContent='No automatic noggin found — center it in the oval.'}}
$('#zoom').oninput=e=>{crop.zoom=+e.target.value;drawCrop()};$('#rotate').onclick=()=>{crop.rot=(crop.rot+90)%360;drawCrop()};
function point(e){const r=cropC.getBoundingClientRect();return{x:(e.clientX-r.left)*700/r.width,y:(e.clientY-r.top)*700/r.height}}
$('#cropStage').onpointerdown=e=>{e.preventDefault();cropC.setPointerCapture(e.pointerId);pointers.set(e.pointerId,point(e));if(pointers.size===1)drag={p:point(e),x:crop.x,y:crop.y};if(pointers.size===2){const a=[...pointers.values()];pinch={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),z:crop.zoom}}};
$('#cropStage').onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,point(e));if(pointers.size===2&&pinch){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);crop.zoom=Math.max(.45,Math.min(3.5,pinch.z*d/pinch.d));$('#zoom').value=crop.zoom}else if(drag){const p=point(e);crop.x=drag.x+p.x-drag.p.x;crop.y=drag.y+p.y-drag.p.y}drawCrop()};
function pointerUp(e){pointers.delete(e.pointerId);drag=null;pinch=null}$('#cropStage').onpointerup=pointerUp;$('#cropStage').onpointercancel=pointerUp;
$('#confirm').onclick=()=>{head=document.createElement('canvas');head.width=head.height=512;const h=head.getContext('2d');h.save();h.beginPath();h.ellipse(256,256,205,250,0,0,Math.PI*2);h.clip();h.translate(256+crop.x*512/700,256+crop.y*512/700);h.rotate(crop.rot*Math.PI/180);const s=crop.base*crop.zoom*512/700;h.scale(s,s);h.drawImage(image,-image.width/2,-image.height/2);h.restore();resetRun();show('game');$('#hint').style.display='block';requestAnimationFrame(loop)};
function renderWeapons(){const order=['hammer','shark','toy'];$('#weapons').innerHTML=order.map((id,i)=>{const open=unlocked.includes(id),cost=i?1:0;return `<button class="weapon ${id===selected?'selected':''} ${open?'':'locked'}" data-id="${id}"><span>${weapons[id].icon}</span>${weapons[id].name}${open?'':`<span class="cost">🟡 ${cost}</span>`}</button>`}).join('');$$('.weapon').forEach(b=>b.onclick=()=>chooseWeapon(b.dataset.id));$('#coins').textContent=coins}
function chooseWeapon(id){if(!unlocked.includes(id)){if(coins<1){toast('FLATTEN A HEAD TO EARN A COIN!');return}const prev=id==='shark'?'hammer':'shark';if(!unlocked.includes(prev)){toast('UNLOCK THE SHARK FIRST!');return}coins--;unlocked.push(id);selected=id;save();toast(id==='shark'?'SHARK: ACQUIRED. INSURANCE: PENDING.':'THE TINIEST TOOL JOINS THE CREW!');coinSound()}else{selected=id;renderWeapons();toast(weapons[id].name+' READY')}}
function resetRun(){flat=0;runWon=false;swinging=false;particles=[];$('#fill').style.width='0';$('#combo').textContent='READY?';renderWeapons()}
function hideWin(){$('#win').classList.remove('show')}
$('#again').onclick=()=>{hideWin();resetRun()};$('#shop').onclick=()=>{hideWin();resetRun();document.querySelector('.weapon.locked')?.animate([{transform:'scale(1)'},{transform:'scale(1.12)'},{transform:'scale(1)'}],500)};
$('#smash').onclick=smash;gameC.onclick=smash;
function smash(){if(!head||swinging||runWon)return;ensureAudio();$('#hint').style.display='none';const w=weapons[selected];swinging=true;swing={t:performance.now(),d:w.speed};setTimeout(()=>impact(w),w.speed*.58)}
function impact(w){flat=Math.min(1,flat+w.damage);shake=selected==='hammer'?16:selected==='shark'?23:8;$('#fill').style.width=(flat*100)+'%';$('#combo').textContent=w.word[Math.floor(Math.random()*w.word.length)];makeSound(selected);makeParticles(w.mess,selected==='shark'?28:selected==='toy'?24:14);if(navigator.vibrate)navigator.vibrate(selected==='shark'?[25,20,35]:selected==='toy'?8:25);if(flat>=.999&&!runWon){runWon=true;setTimeout(win,520)}}
function win(){coins++;save();coinSound();makeParticles('confetti',80);$('#win').classList.add('show');$('#win').setAttribute('aria-hidden','false')}
function toast(t){$('#combo').textContent=t;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#combo').textContent='READY?',1600)}
function ensureAudio(){if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume()}
function osc(type,f0,f1,d,vol=.18){if(!soundOn)return;ensureAudio();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f0,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,f1),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function makeSound(id){if(id==='hammer'){osc('square',120,42,.22,.22);osc('sine',70,30,.32,.3)}else if(id==='shark'){osc('sawtooth',95,28,.45,.25);setTimeout(()=>osc('sine',500,90,.22,.12),60)}else{osc('sine',880,260,.12,.16);setTimeout(()=>osc('square',520,760,.1,.08),90)}}function coinSound(){osc('sine',520,850,.15,.12);setTimeout(()=>osc('sine',750,1200,.2,.12),100)}
$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').textContent='Sound '+(soundOn?'ON':'OFF');if(soundOn)ensureAudio()};
function makeParticles(type,n){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,sp=3+Math.random()*11;particles.push({x:450,y:560,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp-6,life:45+Math.random()*35,type,color:type==='confetti'?['#ffcf40','#f24b3b','#2a73ff','#45c787'][i%4]:'#a87943',r:3+Math.random()*7})}}
function drawHead(){const squash=.86*flat, w=360*(1+flat*.48),h=430*(1-squash);gc.save();gc.translate(450,590-h/2);gc.shadowColor='#171716';gc.shadowBlur=0;gc.shadowOffsetY=18;gc.shadowOffsetX=9;gc.beginPath();gc.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);gc.clip();gc.drawImage(head,-w/2,-h/2,w,h);gc.restore();gc.save();gc.translate(450,590-h/2);gc.strokeStyle='#171716';gc.lineWidth=12;gc.beginPath();gc.ellipse(0,0,w/2,h/2,0,0,Math.PI*2);gc.stroke();gc.restore()}
function drawWeapon(now){if(!swinging)return;const w=weapons[selected],p=Math.min(1,(now-swing.t)/swing.d),angle=p<.58?-.95+(p/.58)*1.6:.65-(p-.58)/.42*.5;gc.save();gc.translate(450,280);gc.rotate(angle);if(selected==='hammer'){gc.fillStyle='#845433';gc.fillRect(-18,-230,36,250);gc.fillStyle='#555';gc.strokeStyle='#171716';gc.lineWidth=10;gc.fillRect(-105,-255,210,85);gc.strokeRect(-105,-255,210,85)}else if(selected==='toy'){gc.fillStyle='#3fc5e8';gc.fillRect(-17,-220,34,230);gc.fillStyle='#ff55a3';gc.strokeStyle='#171716';gc.lineWidth=9;gc.beginPath();gc.roundRect(-110,-252,220,95,35);gc.fill();gc.stroke();gc.fillStyle='#ffcf40';gc.beginPath();gc.arc(-62,-205,21,0,7);gc.arc(62,-205,21,0,7);gc.fill()}else{gc.fillStyle='#2a83b8';gc.strokeStyle='#171716';gc.lineWidth=9;gc.beginPath();gc.moveTo(0,-260);gc.quadraticCurveTo(70,-230,62,-150);gc.lineTo(28,35);gc.lineTo(-28,35);gc.lineTo(-55,-150);gc.quadraticCurveTo(-70,-230,0,-260);gc.fill();gc.stroke();gc.beginPath();gc.moveTo(-48,-207);gc.lineTo(-150,-250);gc.lineTo(-132,-160);gc.closePath();gc.moveTo(48,-207);gc.lineTo(150,-250);gc.lineTo(132,-160);gc.closePath();gc.fill();gc.stroke();gc.fillStyle='white';gc.beginPath();gc.arc(-35,-220,13,0,7);gc.arc(35,-220,13,0,7);gc.fill()}gc.restore();if(p>=1)swinging=false}
function drawParticles(){particles.forEach(q=>{q.x+=q.vx;q.y+=q.vy;q.vy+=.35;q.life--;gc.save();if(q.type==='bubbles'){gc.strokeStyle='#2a73ff';gc.lineWidth=4;gc.beginPath();gc.arc(q.x,q.y,q.r,0,7);gc.stroke()}else{gc.fillStyle=q.color;gc.translate(q.x,q.y);gc.rotate(q.x*.04);q.type==='confetti'?gc.fillRect(-q.r,-q.r/2,q.r*2,q.r):gc.beginPath()||gc.arc(0,0,q.r,0,7)||gc.fill()}gc.restore()});particles=particles.filter(q=>q.life>0&&q.y<900)}
function loop(now){if(!screens.game.classList.contains('active'))return;gc.setTransform(1,0,0,1,0,0);gc.clearRect(0,0,900,850);gc.fillStyle='#ffcf40';gc.beginPath();gc.ellipse(450,650,360,95,0,0,7);gc.fill();gc.strokeStyle='#171716';gc.lineWidth=9;gc.stroke();if(shake){gc.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);shake*=.82}drawHead();drawWeapon(now);drawParticles();requestAnimationFrame(loop)}
$('#how').onclick=()=>$('#help').showModal();$$('.close').forEach(b=>b.onclick=()=>$('#help').close());save();
